### ISSUE TITLE
BL12 - Creating Schedules Checklist

### ISSUE THREAD

**Issue by JoshuaDevine** [fhcds/Residency#1]
# AMION Checklist: 

- [ ] Check Neurology Clinic dates for Tuesday mornings
- [ ] Check Elective clinics 
- [ ] Procedures coverage
- [ ] Colpo – Update Women’s Case Management of dates to fill
- [ ] Faculty PTO
- [ ] Holidays
- [ ] Important Events – Interview days, Retreat, Graduation, Conferences like ALSO, KC
- [ ] Group Classes – Healthy Living and Diabetes Group Visits
- [ ] Nursing Home

# TBD:

- [ ] Ambulatory Tuesday AMs
- [ ] HIV- Either Tuesday or Thursday -All Day Clinics
- [ ] Urgent Care - Either Tuesday or Thursday all-day clinics plus Wed AM CL
- [ ] Electives
- [ ] Peds & Peds Teen 

# Replace Clinics 
- [ ] Residency Chief Admin: `One Half Day Session` Martelly & Matthews
- [ ] Sports Med Track: Mandoyan
- [ ] HIV track/SPNS - Matthews, Dy, Lee, Wang
